{
 "title": "cluster-airflow-LegisFrance",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "airflow_id", "label": "Airflow Instance Id", "query": "label_values(airflow_id)" }
  ]
 },
 "panels": [
  {
   "title": "Scheduler heartbeat",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "af_agg_scheduler_heartbeat{airflow_id=\"$airflow_id\"}"
    }
   ]
  },
  {
   "title": "Executor running tasks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "af_agg_executor_running_tasks{airflow_id=\"$airflow_id\"}"
    }
   ]
  },
  {
   "title": "Total successful tasks",
   "type": "stat",
   "description": "Overall task instances successes",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "af_agg_ti_successes{airflow_id=\"$airflow_id\"}"
    }
   ]
  },
  {
   "title": "Executor failed tasks",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "af_agg_ti_failures", "legendFormat": "tasks failed" }
   ]
  },
  {
   "title": "Success DAG run duration",
   "type": "graph",
   "description": "Seconds taken for a DagRun to reach success state",
   "gridPos": { "h": 9, "w": 22, "x": 1, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "af_agg_dagrun_duration_success{airflow_id=\"airflow\",dag_id=\"legifrance-data-eng\",quantile=\"0.99\"} * 1000"
    }
   ]
  },
  {
   "title": "DAG run dependency check time",
   "type": "graph",
   "description": "Seconds taken to check DAG dependencies",
   "gridPos": { "h": 6, "w": 22, "x": 1, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "af_agg_dagrun_dependency_check{airflow_id=\"airflow\",dag_id=\"legifrance-data-eng\",quantile=\"0.99\"} * 1000"
    }
   ]
  }
 ]
}