{
 "title": "cluster-airflow-LegisFrance",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "airflow_id", "label": "Airflow Instance Id", "query": "label_values(airflow_id)" }
  ]
 },
 "panels": [
  {
   "title": "Scheduler heartbeat",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "af_agg_scheduler_heartbeat{airflow_id=\"$airflow_id\"}"
    }
   ]
  },
  {
   "title": "Tasks Average Durations",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 9, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "1000 * af_agg_dag_task_duration{airflow_id=\"airflow\",dag_id=\"legifrance-data-eng\",task_id=\"fetch-data\",quantile=\"0.99\"}",
     "legendFormat": "{{task_id}}"
    },
    {
     "expr": "1000 * af_agg_dag_task_duration{airflow_id=\"airflow\",dag_id=\"legifrance-data-eng\",task_id=\"load-data\",quantile=\"0.99\"}\r",
     "legendFormat": "{{task_id}}"
    },
    {
     "expr": "1000 * af_agg_dag_task_duration{airflow_id=\"airflow\",dag_id=\"legifrance-data-eng\",task_id=\"create-visualizations\",quantile=\"0.99\"}",
     "legendFormat": "{{task_id}}"
    }
   ]
  },
  {
   "title": "Tasks Failure",
   "type": "graph",
   "description": "Send an alert when a task has failed",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "task_failed{airflow_id=\"airflow\",dag_id=\"legifrance-data-eng\",task_id=\"fetch-data\"}",
     "legendFormat": "{{task_id}}"
    },
    {
     "expr": "task_failed{airflow_id=\"airflow\",dag_id=\"legifrance-data-eng\",task_id=\"load-data\"}",
     "legendFormat": "{{task_id}}"
    },
    {
     "expr": "task_failed{airflow_id=\"airflow\",dag_id=\"legifrance-data-eng\",task_id=\"create-visualizations\"}",
     "legendFormat": "{{task_id}}"
    }
   ]
  },
  {
   "title": "Number of Dag Runs",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "airflow_dag_legifrance_data_eng_dag_duration_count",
     "legendFormat": "number of dag runs"
    }
   ]
  },
  {
   "title": "DAG duration",
   "type": "graph",
   "description": "An indicator to calculate the Legifrance dag duration",
   "gridPos": { "h": 6, "w": 22, "x": 1, "y": 4 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "airflow_dag_legifrance_data_eng_dag_duration{quantile=\"0.5\"}",
     "legendFormat": "DAG duration"
    }
   ]
  },
  {
   "title": "DAG Run Dependency Check Time",
   "type": "graph",
   "description": "Seconds taken to check DAG dependencies",
   "gridPos": { "h": 5, "w": 22, "x": 1, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "af_agg_dagrun_dependency_check{airflow_id=\"airflow\",dag_id=\"legifrance-data-eng\",quantile=\"0.99\"} * 1000"
    }
   ]
  }
 ]
}