version: '3.7'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"
        networks :
            - my-network

    mongodb:
      image: mongo:5.0.16-focal
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
        MONGO_INITDB_DATABASE: legisFrance
      ports:
        - 27017:27017
      volumes:
        - ./mongodb/db_data:/data/db 
        - ./csv_files:/csv_files/
        - ./mongodb/initdb.js:/docker-entrypoint-initdb.d/initdb.js
      networks:
        - my-network


    webserver:
        build:
            context: ./airflow/
            dockerfile: Dockerfile
        restart: always
        depends_on:
            - postgres
            - mongodb
            - chrome
        environment:
            - INSTALL_MYSQL=y
            - LOAD_EX=n
            - EXECUTOR=Local
            - SELENIUM_HOST=chrome
            - SELENIUM_PORT=4444
        # logging:
        #     options:
        #         max-size: 10m
        #         max-file: "3"
        volumes:
            - ./airflow/requirements.txt:/requirements.txt
            - ./airflow/dags:/usr/local/airflow/dags
            - ./mongodb/db_data:/usr/local/airflow/db_data_airflow/
            - ./csv_files:/csv_files
            - ./airflow/visualizations/:/usr/local/airflow/visualizations/
        ports:
            - "8080:8080"
        networks:
            - my-network
        command: webserver

    chrome:
        image: selenium/standalone-chrome:4.9.0
        hostname: chrome
        ports:
            - "4444:4444"
        environment:
            SE_VNC_NO_PASSWORD: 1
            JAVA_OPTS: -Dwebdriver.chrome.whitelistedIps=
        networks:
            - my-network

networks:
  my-network:
    driver: bridge             
