global:
    scrape_interval: 50s
    evaluation_interval: 50s
    scrape_timeout: 20s
    external_labels:
        monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'statsd-exporter'
    static_configs:
      - targets: ['statsd:9102']
      - labels:
          airflow_id: 'airflow'   
  
    tls_config:
      insecure_skip_verify: true